<script lang="ts">
  //Imports
  import getIntegrity from '$lib/integrity';

  //State
  const suggestedVariables = {
    'scheme-main': 'hsl(0, 0%, 10%)',
    'scheme-main-bis': 'hsl(0, 0%, 13%)',
    'scheme-main-ter': 'hsl(0, 0%, 20%)',
    'scheme-invert': 'hsl(0, 0%, 100%)',
    'scheme-invert-bis': 'hsl(0, 0%, 98%)',
    'scheme-invert-ter': 'hsl(0, 0%, 96%)',
    'background': 'hsl(0, 0%, 14%)',
    'text': 'hsl(0, 0%, 71%)',
    'text-strong': 'hsl(0, 0%, 79%)',
    'shadow':
      '0 0.5em 1em -0.125em rgba(hsl(0, 0%, 10%), 0.1), 0 0px 0 1px rgba(hsl(0, 0%, 10%), 0.02)',
  };

  const base =
    typeof window != 'undefined' ? window.location.origin : 'invalid://error';
  const lightUrl = new URL('/api/bulma-0.9.4.min.css', base);
  const darkUrl = new URL('/api/bulma-0.9.4.min.css', base);
  darkUrl.search = new URLSearchParams(suggestedVariables).toString();

  let snippet = '';

  (async () => 
  {
    //Skip if SSR
    if (
      lightUrl.protocol.startsWith('invalid') ||
      darkUrl.protocol.startsWith('invalid')
    ) 
  {
      return;
    }

    //Get the integrities
    const lightIntegrity = await getIntegrity(lightUrl);
    const darkIntegrity = await getIntegrity(darkUrl);

    //Generate the snippet
    snippet = `<link rel="stylesheet" media="(prefers-color-scheme: light)" href="${lightUrl}" integrity="${lightIntegrity}" crossorigin="anonymous">
<link rel="stylesheet" media="(prefers-color-scheme: dark)" href="${darkUrl}" integrity="${darkIntegrity}" crossorigin="anonymous">`;
  })();
</script>

<div class="content full-width has-text-centered mx-6">
  <h1 class="is-size-1">About</h1>

  <!-- Q & A -->
  <h2 class="is-size-4">How does Bulma On Demand work?</h2>
  <p class="is-size-5">
    Bulma On Demand works by running <a
      href="https://sass-lang.com"
      target="_blank"
      rel="noreferer nofollow">SASS</a
    >
    against Bulma using the variables you provide.
  </p>

  <h2 class="is-size-4">When should I use Bulma On Demand?</h2>
  <p class="is-size-5">
    Bulma On Demand is best suited for light-weight websites and microsites
    where you don't want to set up a complicated toolchain just to tweak Bulma,
    but you can use it on any website. However, if you're already using SASS for
    other aspects of your website, you're probably better off just <a
      href="https://bulma.io/documentation/customize"
      rel="noreferer nofollow">customizing Bulma directly</a
    >.
  </p>

  <h2 class="is-size-4">Is Bulma On Demand fast?</h2>
  <p class="is-size-5">
    Yes. You can see this for yourself because this website uses Bulma On
    Demand's API. Bulma On Demand uses an in-memory cache to reduce the number
    of times Bulma is actually recompiled, thereby greatly improving
    performance. This is also why the first request with a given set of
    variables takes longer than successive requests.
  </p>

  <h2 class="is-size-4">Is Bulma On Demand secure?</h2>
  <p class="is-size-5">
    Most likely. Bulma On Demand supports <a
      href="https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity"
      target="_blank"
      rel="noreferer nofollow">subresource integrity hashes</a
    >
    to prevent tampering with the style sheets. Furthermore, Bulma On Demand runs
    the SASS compiler inside of a
    <a
      href="https://github.com/patriksimek/vm2"
      target="_blank"
      rel="noreferer nofollow">VM2 Sandbox</a
    > in the event of a vulnerability in SASS.
  </p>

  <h2 class="is-size-4">Does Bulma On Demand support dark mode?</h2>
  <p class="is-size-5">
    Yes. The best way to add a dark mode is to duplicate the <code>link</code>
    snippet generated by Bulma On Demand. Then add
    <code>media="(prefers-color-scheme: dark)"</code>
    to the one of the links and
    <code>media="(prefers-color-scheme: light)"</code> to the other. This tells
    the browser to only load one of the style sheets depending on the user's
    theming preferences (Learn more
    <a
      href="https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme"
      target="_blank"
      rel="noreferer nofollow">here</a
    >). Finally, change some of the variables in the dark mode CSS URL to make
    Bulma actually dark. Some good defaults are:
  </p>

  <!-- Suggested variables -->
  <table class="is-striped table">
    <!-- Header -->
    <thead>
      <tr>
        <th>Name</th>
        <th>Value</th>
      </tr>
    </thead>

    <!-- Body -->
    <tbody>
      {#each Object.entries(suggestedVariables) as [name, value]}
        <tr>
          <!-- Name -->
          <td>
            <code>{name}</code>
          </td>

          <!-- Value -->
          <td>
            <code>{value}</code>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>

  <p class="is-size-5">
    If you did everything right, you should have something like the following in
    your <a
      href="https://developer.mozilla.org/docs/Web/HTML/Element/head"
      target="_blank"
      rel="noreferer nofollow"><code>head</code> element</a
    >:
  </p>

  <div class="full-width scroll">
    <pre class="has-text-left"><code>{snippet}</code></pre>
  </div>
</div>
